### ISSUE TITLE
postgresql engine

### ISSUE THREAD

**Issue by Adiaphora** [ipoddubny/webcdr#11]
pagination doesn't work.

**Comment by Adiaphora** [comment]
figured it out.
side note: [Issue: node v6 knex anonymous](https://github.com/brianc/node-postgres/issues/1062)

1. postgress `count(*)` returns column named 'count', unlike mysql
therefore `cnt = count[0]['count(*)']` results undefined. totalEntries gracefully ignores this fact.
2. next thing. after  the fieldname correction, suddenly - "totalEntries must be an integer"), had to wrap cnt into parseInt

**Comment by ipoddubny** [comment]
Thank you for the bug report. It should be fixed now.
