### ISSUE TITLE
outbound  filter view problem

### ISSUE THREAD

**Issue by leicalist** [ipoddubny/webcdr#14]
Hello!
When the "outgoing" filter is turned on, only calls with the status "not answered" are displayed. My Asterisk is a default Freepbx 13, in the cdr table I added only the id column. I do not quite understand how the webcdr divides the direction of the calls, could you explain it.

**Comment by ipoddubny** [comment]
In case if the question is relevant: it's hardcoded based on length of `src` and `dst`, see https://github.com/ipoddubny/webcdr/blob/master/lib/api/cdrs.js#L76-L78
