### ISSUE TITLE
Не видно записей разговора

### ISSUE THREAD

**Issue by bondarenkoigor** [ipoddubny/webcdr#18]
Здравствуйте! Поставил и запустил вашу CDRку, сами записи о звонках из базы полностью выгребаются, все окей, а вот запись звонка (mp3) я к сожалению не вижу. Она просто тупо не отображается. В config.ini прописал pattern = /var/spool/asterisk/monitor/%uniqueid%.mp3 так как записи все у меня лежат в одной папке... записи звонков есть, c базой все впорядке... Не подскажите как может отдебажить этот момент?

**Comment by ipoddubny** [comment]
Код интерфейса ожидает, что диалплан использует cdr_adaptive_odbc и отмечает CDR с записью разговоров, записывая uniqueid звонка в колонку record. Если ваш диалплан этого не делает, можете создать view-обёртку над cdr, в котором будут все те же колонки, но record=uniqueid. Но в таком случае записи будут отображаться у всех звонков, даже если файлов нет.

**Comment by iGor3kUA** [comment]
А нельзя просто где-то в коде поправить чтоб он лез не в поле record, а в uniqueid ? Просто я в JSе вообще не очень чтоб дописывать, а делать еще одну колонку в таблице, переносить существующие данные (а их там за несколько лет целая куча собралась) и переделывать через cdr_adaptive_odbc слишком долго)
