### ISSUE TITLE
"чистый экран" после логина

### ISSUE THREAD

**Issue by asteriskauto** [ipoddubny/webcdr#19]
Добрый день. Вроде бы сделал все по мануалу, однако после логина вижу "чистый экран", ничего не отображается, в логе node - 200 везде
https://hastebin.com/upilonoxer.vbs

 В логе мускуля - все чисто, ngrep по порту мускуля говорит - https://hastebin.com/baxugehulo.scala

В консоли ошибка:

Uncaught TypeError: Cannot read property 'radio' of undefined
    at constructor._initChannel (bundle.js:3236)
    at new constructor (bundle.js:3104)
    at Object.<anonymous> (bundle.js:35274)
    at Object.44../admin (bundle.js:35378)
    at s (bundle.js:1)
    at e (bundle.js:1)
    at bundle.js:1

решение из https://github.com/ipoddubny/webcdr/issues/2 не помогло

node -v
v6.13.0

Подскажите куда копать?

**Comment by ipoddubny** [comment]
Проблема в сборке фронтэнда. Должно быть исправлено последним коммитом.
