### ISSUE TITLE
Build frontend

### ISSUE THREAD

**Issue by vlad-dc** [ipoddubny/webcdr#22]
Hello, 
I have an issue to build the frontend.
----------------------------------------------------------
> webcdr@0.9.0 build /var/www/html/webcdr
> browserify public/js/main.js -o public/js/build/bundle.js

Error: Cannot find module 'backbone.wreqr' from '/var/www/html/webcdr/public/js'
    at /var/www/html/webcdr/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/var/www/html/webcdr/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/var/www/html/webcdr/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/var/www/html/webcdr/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/var/www/html/webcdr/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /var/www/html/webcdr/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

npm ERR! Linux 3.10.0-327.10.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v4.9.1
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! webcdr@0.9.0 build: `browserify public/js/main.js -o public/js/build/bundle.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webcdr@0.9.0 build script 'browserify public/js/main.js -o public/js/build/bundle.js'.
npm ERR! This is most likely a problem with the webcdr package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browserify public/js/main.js -o public/js/build/bundle.js
----------------------------------------------------------
How can I solve this?
Thank you in advance.

Vlad.

**Comment by ipoddubny** [comment]
``backbone.wreqr`` is not installed. Have you run ``npm install``?

**Comment by vlad-dc** [comment]
Yes but with warnings:

npm install
npm WARN package.json backbone.wreqr@1.4.0 bugs['web'] should probably be bugs['url'].
npm WARN package.json backbone.wreqr@1.4.0 No license field.
npm WARN deprecated connect@2.7.11: connect 2.x series is deprecated
npm WARN deprecated coffee-script@1.3.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated formatio@1.0.2: This package is unmaintained. Use @sinonjs/formatio instead
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.1.14: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated minimatch@0.4.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN cannot run in wd phantomjs@1.9.20 node install.js (wd=/var/www/html/backbone.wreqr/node_modules/grunt-contrib-jasmine/node_modules/grunt-lib-phantomjs/node_modules/phantomjs)

Do yo know another way to install backbone.wreqr ??

**Comment by ipoddubny** [comment]
What node.js and npm versions do you have?

**Comment by vlad-dc** [comment]
I have:
node v4.9.1
npm  v2.15.11

**Comment by vlad-dc** [comment]
Hello Ivan,

I had reinstalled node and npm to have:

Name        : nodejs
Arch        : x86_64
Epoch       : 1
Version     : 6.14.3
Release     : 1.el7

Name        : nodejs
Arch        : x86_64
Epoch       : 2
Version     : 8.11.3

And work fine.

Thanks a lot.

**Comment by ipoddubny** [comment]
👍
