### ISSUE TITLE
calendar russia language, not english

### ISSUE THREAD

**Issue by itcuibap03** [ipoddubny/webcdr#7]
calendar russia language, not english
Please change to English

**Comment by ipoddubny** [comment]
When I change language to English, everything including calendars is in English. When I choose Russian, everything is in Russian. Please, provide more detail on how to reproduce the bug.

**Comment by itcuibap03** [comment]
Please see image
http://prnt.sc/e1f8va

**Comment by ipoddubny** [comment]
You're totally right, should be fixed now.
